import IISKursovayaRabotaIspravlenoПроверкаКиоскаEController from '../i-i-s-kursovaya-rabota-ispravleno-проверка-киоска-e';

var IISKursovayaRabotaIspravlenoПроверкаКиоскаENewController = IISKursovayaRabotaIspravlenoПроверкаКиоскаEController;
export default IISKursovayaRabotaIspravlenoПроверкаКиоскаENewController;
