import IISKursovayaRabotaIspravlenoОператорEController from '../i-i-s-kursovaya-rabota-ispravleno-оператор-e';

var IISKursovayaRabotaIspravlenoОператорENewController = IISKursovayaRabotaIspravlenoОператорEController;
export default IISKursovayaRabotaIspravlenoОператорENewController;
